server:
  port: 9501

spring:
  application:
    name: gateway-service
  redis:
    host: localhost
    port: 6379

  resources:
    static-locations:
        - "classpath:/static/"
        - "file:///E:/code2025/Microservices/RecruitmentSystem/gateway-service/src/main/resources/uploads/"

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:7001/eureka
zuul:
  routes:
    auth-service:
      path: /auth/**
      serviceId: auth-service
      strip-prefix: false
    user-service:
      path: /user/**
      serviceId: user-service
      strip-prefix: false
    job-service:
      path: /jobs/**
      serviceId: job-service
      strip-prefix: false
    resume-service:
      path: /resume/**
      serviceId: resume-service
      strip-prefix: false
    admin-service:
      path: /admin/**
      serviceId: admin-service
      strip-prefix: false
  sensitive-headers:
  add-host-header: true


