# 配置文件
server:
  port: 8702

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/teamprojectuser?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:7001/eureka

mybatis:
  type-aliases-package: cn.cuit.userservice.Entity
  mapper-locations: classpath:/mapper/*.xml