server:
  port: 8085

spring:
  application:
    name: notify-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recruitmentSystem_notify?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: "041020"
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    enabled: true
    connection-timeout: 5000
    requested-heartbeat: 30
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-interval: 10000
          multiplier: 2.0
          max-attempts: 3
        default-requeue-rejected: true
        acknowledge-mode: auto
        prefetch: 1
        concurrency: 1
        max-concurrency: 5

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:7001/eureka
    enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    
feign:
  hystrix:
    enabled: true
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
            
springfox:
  documentation:
    swagger-ui:
      enabled: false
    enabled: false

rabbitmq:
  exchange:
    interview: interview.exchange
    application: application.exchange
  queue:
    interview-notification: interview.notification.queue
    application-notification: application.notification.queue
  routing-key:
    interview-notification: interview.notification
    application-notification: application.notification.routing-key

springdoc:
  api-docs:
    enabled: false
    path: /api-docs
  swagger-ui:
    enabled: false
    path: /swagger-ui.html