# 配置文件

server:
  port: 8086

spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:mysql://localhost:3306/recruitment_admin?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:7001/eureka
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        requestInterceptors:
                - cn.cuit.adminservice.config.FeignAuthInterceptor


logging:
  level:
    cn.cuit.admin-service: debug
