server:
  port: 9501


spring:
  application:
    name: gateway-service
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:7001/eureka
zuul:
  routes:
    auth-service:
      path: /auth/**
      serviceId: auth-service
      strip-prefix: false
    user-service:
      path: /user/**
      serviceId: user-service
    resume-service:
      path: /resume/**
      serviceId: resume-service
  sensitive-headers:
  add-host-header: true


