# 配置文件
server:
  port: 8601

spring:
  application:
    name: job-service

  datasource:
    url: jdbc:mysql://localhost:3306/teamprojectjob?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

mybatis:
  type-aliases-package: cn.cuit.jobservice.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:                                         # 客户端进行Eureka注册的配置
    service-url:                                  # 定义Eureka服务地址
      defaultZone: http://admin:123456@localhost:7001/eureka
  instance:
    instance-id: job-8601.com                  # 显示主机名称




logging:
  level:
    cn.cuit: debug
